### ISSUE TITLE
add support for namespace in http headers

### ISSUE THREAD

**Issue by gravesti** [vimc/vaultr#38]
Our vault setup uses [namespaces](https://developer.hashicorp.com/vault/tutorials/enterprise/namespaces) and LDAP auth.

I think the easiest way to get this working with `vaultr` is to send the namespace with the http requests. I've got a branch with this working by adding support for arbitrary http headers in the `vault_client` object.
https://github.com/gravesti/vaultr/tree/add-namespaces

I still need to add some tests but I don't think the open source vault has namespace support. How should we proceed?

**Comment by gravesti** [comment]
Thanks for this @richfitz ! In my testing it works as expected.

**Comment by richfitz** [comment]
Thanks, that's merged now. It might be a while before we push it to CRAN - please let us know in the meantime if you hit any issues

**Comment by richfitz** [comment]
Fixed in #40
