### ISSUE TITLE
support ldap authentication

### ISSUE THREAD

**Issue by But2ene** [vimc/vaultr#42]
Hi,

we are interested in using {vaultr} at work, but some part of our code require an authentication with "ldap". There are workarounds, but it is cleaner to add this functionnality.

I saw in other issues that you can only test what is available on your stack. Would you be open to contribution on that part ? If you accept a PR, how long would it take to deploy it on CRAN ? (I'm asking because our proxy blocks github, but we have access to CRAN)

**Comment by But2ene** [comment]
Thank you for the quick answer ! I've started developing something on #43 and it is not functionnal yet.

Actually, it's not really necessary for my company to have it on CRAN, there are manual workarounds for using the updated package (which are not r-universe). I'll keep you updated on the tests in production.

**Comment by But2ene** [comment]
I could login and get some secrets !

```r
v$login(
  username = Sys.getenv("KYSS_LDAP_USERNAME"),
  password = Sys.getenv("KYSS_LDAP_PASSWORD"),
  method = "ldap",
  mount = "*********"
)
  
v$read("/secret/****/****/****/****/hdfs")
#> returns stuff
```

I'll try to get some help to setup test environment.

**Comment by fh-mthomson** [comment]
Adding my perspective that both would be very helpful:
* Adding `ldap` support 
* Publishing to CRAN

A `vault login` CLI approach works as a bandaid, but being able to just use a consolidated `vaultr` would be very welcome for many end users.

**Comment by richfitz** [comment]
Right, apologies for the delay on this.

@But2ene, thanks for your initial work on #43; I've opted do do a clean implementation with no licencing implications.

Please see #46 for the implementation - if you can check this against your stacks that would be much appreciated. I imagine that it should work though as you're unlikely to be doing any actual configuration of vault from vaultr, just logging in. I'll comment further on that PR
